### ISSUE TITLE
Explique ton code

### ISSUE THREAD

**Issue by JeffAbrahamson** [Killy85/MachineLearningExercises#1]
Suggestion générale : commente ton code et organise en fonction.  Utilise pylint.

https://stackoverflow.com/questions/356161/python-coding-standards-best-practices#356238

En outre, utilise quelque chose comme ceci :

```
def main():
    """...
    """

if __name__ == "__main__":
    main()
```

**Comment by Killy85** [comment]
I'm working on this atm, but I also made a pretty complete ReadMe, which may be kind of a documentation for people wanting to know what the code is about.

Of course it is important to also explain the way it work.

**Comment by JeffAbrahamson** [comment]
README's are good for design documents and explaining systems, but explaining code should usually be with the code.  When reading the code, it's not good to depend on the reader thinking to look at a different document.
