### ISSUE TITLE
et puis 03/

### ISSUE THREAD

**Issue by JeffAbrahamson** [Killy85/MachineLearningExercises#4]
```
╭╴ (master=) [virt]╶╮
╰ vagrant@ubuntu-xenial:03 $ python logistic_regression.py 
  File "logistic_regression.py", line 61
    Precision {precision:.2f}% \n    Recall {recall:.2f}% \n    F1 measure {f_measure:.2f}%\n    Correctness {prct:.2f}%""")
                                                                                                                          ^
SyntaxError: invalid syntax
╭╴ (master=) [virt]╶╮
╰ 1, vagrant@ubuntu-xenial:03 $ 
```

**Comment by Killy85** [comment]
Hey,

Thanks for the feedback.

Which version of python are you running? If under 3.6, you may have to upgrade. In fact, I did try this doing a clean install on a docker solution and it runs smoothly with Python3.6.

**Comment by JeffAbrahamson** [comment]
Ah, right, I'm running these in vagrant, and I see my vagrant box is not up to date, so I got python 3.5.x.  I'll upgrade the vagrant instance, then pip, then try again.  I'll get some sleep whilst it does that. ;-)
